{
    'name': 'Republica Dominicana - Comprobantes Fiscales (NCF)',
    'version': '17.0.1.1.0',
    'summary': 'Gestion de NCF para Republica Dominicana segun normativa DGII',
    'description': 'Modulo de Comprobantes Fiscales para Republica Dominicana',
    'author': 'ByChrixDev',
    'website': 'https://github.com/CristianBackend',
    'category': 'Accounting/Localizations',
    'license': 'LGPL-3',
    'depends': ['base', 'account', 'l10n_do', 'contacts', 'web'],
    'data': [
        'security/ncf_security.xml',
        'security/ir.model.access.csv',
        'data/ncf_type_data.xml',
        'data/ir_sequence_data.xml',
        'wizards/dgii_report_wizard_views.xml',
        'views/license_config_views.xml',
        'views/ncf_type_views.xml',
        'views/ncf_sequence_views.xml',
        'views/account_move_views.xml',
        'views/res_partner_views.xml',
        'views/res_company_views.xml',
        'views/menu_views.xml',
        'reports/invoice_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'l10n_do_ncf/static/src/css/ncf_styles.css',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
